version: "3"

networks:
  proxy-network:
    external: true

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    restart: "unless-stopped"
    command:
      # Enable the dashboard
      - "--api.dashboard=true"
      # Setup the docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy-network"
      # Create http and https entrypoints
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    ports:
      # Expose http and https port
      - "80:80"
      - "443:443"
    networks:
      - "proxy-network"
    volumes:
      # Mount the docker socket read-only
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${DASHBOARD_HOST}`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
